"""
Platform Returns Processing Script for C2PA Robustness Testing
==============================================================

This script processes assets downloaded from social media platforms after
manual upload/download round-trip testing. It verifies C2PA signatures,
calculates quality metrics, and merges with manual logging data.

Workflow:
1. Scan platform returned/ folders for downloaded files
2. Parse filename convention to extract metadata
3. Run C2PA verification using verify_c2pa.py logic
4. Calculate quality metrics using calculate_quality_metrics.py logic
5. Load manual CSV log (platform_manifest.csv)
6. Join automated metrics with manual logs
7. Generate platform_results.csv

Research Context:
- Tests real-world C2PA manifest persistence through platform round-trips
- Most platforms are expected to STRIP C2PA manifests during transcoding
- Quality degradation varies by platform compression policies

Usage:
    python scripts/platform/process_platform_returns.py

    Processes all files in platform_tests/*/returned/ folders
    Outputs to: data/metrics/platform_results.csv

File Naming Convention (from prepare_platform_uploads.py):
    {original}__{platform}__{mode}__{timestamp}.{ext}
    Example: seed42_h264_bitrate2000k__instagram__reel__20250112-143022.mp4
"""

import logging
import sys
import subprocess
import json
import csv
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, Tuple, List
import time

import cv2
import numpy as np
import pandas as pd

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('data/platform_tests/processing.log')
    ]
)

# Configuration
PLATFORM_TESTS_BASE = Path("data/platform_tests")
RESULTS_DIR = Path("data/metrics")
MANIFESTS_IMAGES_DIR = Path("data/manifests/images")
MANIFESTS_VIDEOS_DIRS = [
    Path("data/manifests/videos/internal"),
    Path("data/manifests/videos/external")
]
TRANSFORMED_BASE = Path("data/transformed")

# C2PA tool path (local installation)
C2PATOOL_PATH = Path("tools/c2patool/c2patool/c2patool.exe")

# Filename pattern: {original}__{platform}__{mode}__{timestamp}.{ext}
FILENAME_PATTERN = re.compile(r'^(.+)__([^_]+)__([^_]+)__(\d{8}-\d{6})\.(mp4|jpg|png|jpeg|mov|avi)$')


def parse_filename(filename: str) -> Optional[Dict]:
    """
    Parse platform return filename to extract metadata.

    Args:
        filename: Filename following convention

    Returns:
        Dict with parsed metadata or None
    """
    match = FILENAME_PATTERN.match(filename)
    if not match:
        logging.warning(f"Filename does not match convention: {filename}")
        return None

    return {
        'original_filename': match.group(1),
        'platform': match.group(2),
        'mode': match.group(3),
        'timestamp': match.group(4),
        'extension': match.group(5)
    }


def detect_media_source(original_filename: str) -> str:
    """
    Detect if media is internal or external based on filename pattern.

    Internal media (generated by our pipeline) contains 'seed' in the filename.
    External media (from Sora, Veo, Midjourney, etc.) does not contain 'seed'.

    Args:
        original_filename: Base filename without extension (e.g., "video_22_signed" or "img_003_seed45_signed")

    Returns:
        "internal" if filename contains 'seed', "external" otherwise
    """
    import re

    # Check if filename contains 'seed' pattern (e.g., seed42, seed100)
    if re.search(r'seed\d+', original_filename):
        return "internal"
    else:
        return "external"


def get_model_version(original_filename: str, asset_type: str, media_source: str) -> str:
    """
    Get model version based on asset type and media source.

    Args:
        original_filename: Base filename
        asset_type: 'image' or 'video'
        media_source: 'external' or 'internal'

    Returns:
        Model version string (SD1.4, SVD, or Veo3.1)
    """
    if asset_type == 'image':
        return 'SD1.4'

    if media_source == 'external':
        return 'Veo3.1'
    else:
        return 'SVD'


def find_original_asset(base_filename: str, asset_type: str) -> Optional[Path]:
    """
    Find the original signed asset to compare against.

    Args:
        base_filename: Base filename without platform suffix
                      e.g., "img_003_seed45_20251113_233209_signed" or "video_22_signed"
        asset_type: 'image' or 'video'

    Returns:
        Path to original signed asset or None
    """
    # Images: img_NNN_seedXX_TIMESTAMP_signed.png
    # Videos: video_N_signed.mp4

    if asset_type == 'image':
        # Look for the exact filename + .png extension
        original_filename = f"{base_filename}.png"
        original_path = MANIFESTS_IMAGES_DIR / original_filename
        if original_path.exists():
            return original_path

        logging.warning(f"Original image not found: {original_filename}")
        return None
    else:
        # Look for the exact filename + .mp4 extension
        original_filename = f"{base_filename}.mp4"
        for video_dir in MANIFESTS_VIDEOS_DIRS:
            original_path = video_dir / original_filename
            if original_path.exists():
                return original_path

        logging.warning(f"Original video not found: {original_filename}")
        return None


def verify_c2pa(file_path: Path) -> Dict:
    """
    Verify C2PA manifest (reused from verify_c2pa.py).

    Args:
        file_path: Path to file

    Returns:
        Dict with verification results
    """
    start_time = time.time()

    try:
        cmd = [
            str(C2PATOOL_PATH),
            str(file_path)
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60
        )

        elapsed_ms = (time.time() - start_time) * 1000

        if result.returncode == 0:
            try:
                manifest_data = json.loads(result.stdout)
                active_manifest = manifest_data.get('active_manifest')

                if active_manifest:
                    # Extract verification metrics
                    claim_signature = active_manifest.get('claim_signature', {})
                    signature_valid = 1 if claim_signature.get('validated') else 0

                    # Check hash match (both dataHash and bmffHash)
                    hash_match = 0
                    assertions = active_manifest.get('assertions', [])
                    for assertion in assertions:
                        if 'dataHash' in assertion:
                            if assertion['dataHash'].get('match', False):
                                hash_match = 1
                        elif 'bmffHash' in assertion:
                            if assertion['bmffHash'].get('match', False):
                                hash_match = 1

                    # Check assertion URIs
                    assertion_uris_match = 1
                    for assertion in assertions:
                        if 'hashedURI' in assertion:
                            if not assertion['hashedURI'].get('match', False):
                                assertion_uris_match = 0
                                break

                    # Overall verification
                    verified = 1 if signature_valid and hash_match else 0

                    # Trust status (informational)
                    signing_credential = active_manifest.get('signingCredential', {})
                    trust_verified = 0 if 'untrusted' in signing_credential else 1

                    validation_state = claim_signature.get('validation_state', 'unknown')

                    return {
                        'manifest_present': 1,
                        'verified': verified,
                        'signature_valid': signature_valid,
                        'hash_match': hash_match,
                        'assertion_uris_match': assertion_uris_match,
                        'trust_verified': trust_verified,
                        'validation_state': validation_state,
                        'failure_reason': '' if verified else 'Hash or signature mismatch',
                        'processing_time_ms': elapsed_ms
                    }

            except json.JSONDecodeError:
                pass

        # No manifest or invalid
        return {
            'manifest_present': 0,
            'verified': 0,
            'signature_valid': 0,
            'hash_match': 0,
            'assertion_uris_match': 0,
            'trust_verified': 0,
            'validation_state': 'no_manifest',
            'failure_reason': 'manifest_dropped',
            'processing_time_ms': elapsed_ms
        }

    except Exception as e:
        elapsed_ms = (time.time() - start_time) * 1000
        logging.error(f"C2PA verification failed for {file_path.name}: {e}")
        return {
            'manifest_present': 0,
            'verified': 0,
            'signature_valid': 0,
            'hash_match': 0,
            'assertion_uris_match': 0,
            'trust_verified': 0,
            'validation_state': 'error',
            'failure_reason': f'Verification error: {str(e)[:100]}',
            'processing_time_ms': elapsed_ms
        }


def calculate_image_metrics(original_path: Path, platform_path: Path) -> Dict:
    """
    Calculate PSNR and SSIM for images with aspect ratio alignment.

    Calculates quality metrics in two modes:
    1. Stretched metrics (psnr, ssim): Scales platform image to match original dimensions
    2. Aligned metrics (psnr_aligned, ssim_aligned): Crops original to match platform aspect ratio

    Args:
        original_path: Path to original signed image
        platform_path: Path to platform-returned image

    Returns:
        Dict with quality metrics: psnr, ssim, psnr_aligned, ssim_aligned, alignment_method,
        lossless_match, processing_time_ms
    """
    start_time = time.time()

    try:
        # Load images
        img_orig = cv2.imread(str(original_path))
        img_platform = cv2.imread(str(platform_path))

        if img_orig is None or img_platform is None:
            return {
                'psnr': 'NA',
                'ssim': 'NA',
                'psnr_aligned': 'NA',
                'ssim_aligned': 'NA',
                'vmaf': 'NA',
                'vmaf_aligned': 'NA',
                'alignment_method': 'error',
                'lossless_match': 0,
                'processing_time_ms': (time.time() - start_time) * 1000
            }

        # Get dimensions
        orig_h, orig_w = img_orig.shape[:2]
        platform_h, platform_w = img_platform.shape[:2]

        # Calculate aspect ratios
        orig_aspect = orig_w / orig_h
        platform_aspect = platform_w / platform_h
        aspect_changed = abs(orig_aspect - platform_aspect) > 0.01

        # ========== STRETCHED METRICS (traditional method) ==========
        # Scale platform image to match original dimensions
        img_platform_stretched = cv2.resize(img_platform, (orig_w, orig_h), interpolation=cv2.INTER_CUBIC)

        # Calculate PSNR (stretched)
        psnr_value = cv2.PSNR(img_orig, img_platform_stretched)
        if psnr_value >= 100.0:
            psnr = "inf"
            lossless_match = 1
        else:
            psnr = f"{psnr_value:.4f}"
            lossless_match = 0

        # Calculate SSIM (stretched)
        from skimage.metrics import structural_similarity
        gray_orig = cv2.cvtColor(img_orig, cv2.COLOR_BGR2GRAY)
        gray_platform_stretched = cv2.cvtColor(img_platform_stretched, cv2.COLOR_BGR2GRAY)
        ssim_value = structural_similarity(gray_orig, gray_platform_stretched)
        ssim = f"{ssim_value:.6f}"

        # ========== ALIGNED METRICS (aspect ratio-aware) ==========
        if aspect_changed:
            # Aspect ratio changed - crop original to match platform aspect ratio
            if orig_w > orig_h and platform_w == platform_h:
                # Horizontal to square crop - center crop original
                crop_w = orig_h
                crop_x = (orig_w - crop_w) // 2
                img_orig_cropped = img_orig[:, crop_x:crop_x+crop_w]
                alignment_method = 'crop_reference_center_square'

            elif orig_h > orig_w and platform_w == platform_h:
                # Vertical to square crop - center crop original
                crop_h = orig_w
                crop_y = (orig_h - crop_h) // 2
                img_orig_cropped = img_orig[crop_y:crop_y+crop_h, :]
                alignment_method = 'crop_reference_center_square'

            else:
                # Unknown aspect ratio change - scale both to minimum
                common_w = min(orig_w, platform_w)
                common_h = min(orig_h, platform_h)
                img_orig_cropped = cv2.resize(img_orig, (common_w, common_h), interpolation=cv2.INTER_CUBIC)
                alignment_method = 'scale_both_to_minimum'

            # Scale platform to match cropped original dimensions
            cropped_h, cropped_w = img_orig_cropped.shape[:2]
            img_platform_aligned = cv2.resize(img_platform, (cropped_w, cropped_h), interpolation=cv2.INTER_CUBIC)

            # Calculate aligned PSNR
            psnr_aligned_value = cv2.PSNR(img_orig_cropped, img_platform_aligned)
            if psnr_aligned_value >= 100.0:
                psnr_aligned = "inf"
            else:
                psnr_aligned = f"{psnr_aligned_value:.4f}"

            # Calculate aligned SSIM
            gray_orig_cropped = cv2.cvtColor(img_orig_cropped, cv2.COLOR_BGR2GRAY)
            gray_platform_aligned = cv2.cvtColor(img_platform_aligned, cv2.COLOR_BGR2GRAY)
            ssim_aligned_value = structural_similarity(gray_orig_cropped, gray_platform_aligned)
            ssim_aligned = f"{ssim_aligned_value:.6f}"

        else:
            # Same aspect ratio - aligned = stretched
            psnr_aligned = psnr
            ssim_aligned = ssim
            alignment_method = 'same_aspect_ratio'

        elapsed_ms = (time.time() - start_time) * 1000

        return {
            'psnr': psnr,
            'ssim': ssim,
            'psnr_aligned': psnr_aligned,
            'ssim_aligned': ssim_aligned,
            'vmaf': 'NA',
            'vmaf_aligned': 'NA',
            'alignment_method': alignment_method,
            'lossless_match': lossless_match,
            'processing_time_ms': elapsed_ms
        }

    except Exception as e:
        logging.error(f"Image metrics calculation failed: {e}")
        elapsed_ms = (time.time() - start_time) * 1000
        return {
            'psnr': 'NA',
            'ssim': 'NA',
            'psnr_aligned': 'NA',
            'ssim_aligned': 'NA',
            'vmaf': 'NA',
            'vmaf_aligned': 'NA',
            'alignment_method': 'error',
            'lossless_match': 0,
            'processing_time_ms': elapsed_ms
        }


def calculate_video_vmaf(original_path: Path, platform_path: Path) -> Dict:
    """
    Calculate comprehensive VMAF for videos with aspect ratio handling.

    Calculates two VMAF scores:
    1. vmaf: Traditional method - scales distorted to reference dimensions
    2. vmaf_aligned: Intelligent alignment (crops reference if aspect ratio changed)

    Args:
        original_path: Path to original signed video
        platform_path: Path to platform-returned video

    Returns:
        Dict with both VMAF scores and method description
    """
    start_time = time.time()

    try:
        # Get video properties using ffprobe
        def get_video_properties(video_path: Path) -> Optional[Tuple[int, int, str]]:
            cmd = [
                'ffprobe',
                '-v', 'error',
                '-select_streams', 'v:0',
                '-show_entries', 'stream=width,height,r_frame_rate',
                '-of', 'csv=p=0',
                str(video_path)
            ]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=True)
            output = result.stdout.strip()
            parts = output.split(',')
            return int(parts[0]), int(parts[1]), parts[2]

        ref_width, ref_height, ref_fps = get_video_properties(original_path)
        dist_width, dist_height, dist_fps = get_video_properties(platform_path)

        # Calculate aspect ratios
        ref_aspect = ref_width / ref_height
        dist_aspect = dist_width / dist_height
        aspect_changed = abs(ref_aspect - dist_aspect) > 0.01

        vmaf = 'NA'
        vmaf_aligned = 'NA'
        method = 'none'

        # VMAF 1: Traditional method - scale distorted to reference
        if (dist_width != ref_width or dist_height != ref_height or dist_fps != ref_fps):
            filter_chain_stretched = (
                f"[0:v]scale={ref_width}:{ref_height}:flags=lanczos,"
                f"fps={ref_fps},format=yuv420p,setpts=PTS-STARTPTS[dist];"
                f"[1:v]format=yuv420p,setpts=PTS-STARTPTS[ref];"
                f"[dist][ref]libvmaf=log_fmt=json:log_path=NUL"
            )
        else:
            filter_chain_stretched = "[0:v]setpts=PTS-STARTPTS[dist];[1:v]setpts=PTS-STARTPTS[ref];[dist][ref]libvmaf=log_fmt=json:log_path=NUL"

        cmd_stretched = [
            'ffmpeg',
            '-i', str(platform_path),  # distorted
            '-i', str(original_path),  # reference
            '-filter_complex', filter_chain_stretched,
            '-f', 'null',
            '-'
        ]

        result_stretched = subprocess.run(cmd_stretched, capture_output=True, text=True, timeout=300)
        vmaf_match = re.search(r'VMAF score:\s*([\d.]+)', result_stretched.stderr)
        if vmaf_match:
            vmaf = f"{float(vmaf_match.group(1)):.4f}"

        # VMAF 2: Aligned (intelligent cropping/scaling)
        if aspect_changed:
            # Aspect ratio changed - likely platform cropped the video
            # Crop reference to match distorted aspect ratio
            if ref_width > ref_height and dist_width == dist_height:
                # Horizontal to square crop - center crop reference
                crop_width = ref_height
                crop_x = (ref_width - crop_width) // 2
                method = 'crop_reference_center_square'

                filter_chain_aligned = (
                    f"[1:v]crop={crop_width}:{ref_height}:{crop_x}:0,"
                    f"scale={dist_width}:{dist_height}:flags=lanczos,"
                    f"fps={dist_fps},format=yuv420p,setpts=PTS-STARTPTS[ref];"
                    f"[0:v]fps={dist_fps},format=yuv420p,setpts=PTS-STARTPTS[dist];"
                    f"[dist][ref]libvmaf=log_fmt=json:log_path=NUL"
                )
            elif ref_height > ref_width and dist_width == dist_height:
                # Vertical to square crop - center crop reference
                crop_height = ref_width
                crop_y = (ref_height - crop_height) // 2
                method = 'crop_reference_center_square'

                filter_chain_aligned = (
                    f"[1:v]crop={ref_width}:{crop_height}:0:{crop_y},"
                    f"scale={dist_width}:{dist_height}:flags=lanczos,"
                    f"fps={dist_fps},format=yuv420p,setpts=PTS-STARTPTS[ref];"
                    f"[0:v]fps={dist_fps},format=yuv420p,setpts=PTS-STARTPTS[dist];"
                    f"[dist][ref]libvmaf=log_fmt=json:log_path=NUL"
                )
            else:
                # Unknown aspect ratio change - scale both to smaller dimension
                common_width = min(ref_width, dist_width)
                common_height = min(ref_height, dist_height)
                method = 'scale_both_to_minimum'

                filter_chain_aligned = (
                    f"[0:v]scale={common_width}:{common_height}:flags=lanczos,"
                    f"fps={dist_fps},format=yuv420p,setpts=PTS-STARTPTS[dist];"
                    f"[1:v]scale={common_width}:{common_height}:flags=lanczos,"
                    f"fps={dist_fps},format=yuv420p,setpts=PTS-STARTPTS[ref];"
                    f"[dist][ref]libvmaf=log_fmt=json:log_path=NUL"
                )

            cmd_aligned = [
                'ffmpeg',
                '-i', str(platform_path),
                '-i', str(original_path),
                '-filter_complex', filter_chain_aligned,
                '-f', 'null',
                '-'
            ]

            result_aligned = subprocess.run(cmd_aligned, capture_output=True, text=True, timeout=300)
            vmaf_match_aligned = re.search(r'VMAF score:\s*([\d.]+)', result_aligned.stderr)
            if vmaf_match_aligned:
                vmaf_aligned = f"{float(vmaf_match_aligned.group(1)):.4f}"
        else:
            # Same aspect ratio - aligned = vmaf
            vmaf_aligned = vmaf
            method = 'same_aspect_ratio'

        elapsed_ms = (time.time() - start_time) * 1000

        return {
            'psnr': 'NA',
            'ssim': 'NA',
            'psnr_aligned': 'NA',
            'ssim_aligned': 'NA',
            'vmaf': vmaf,
            'vmaf_aligned': vmaf_aligned,
            'alignment_method': method,
            'lossless_match': 0,
            'processing_time_ms': elapsed_ms
        }

    except Exception as e:
        logging.error(f"VMAF calculation failed: {e}")
        elapsed_ms = (time.time() - start_time) * 1000
        return {
            'psnr': 'NA',
            'ssim': 'NA',
            'psnr_aligned': 'NA',
            'ssim_aligned': 'NA',
            'vmaf': 'NA',
            'vmaf_aligned': 'NA',
            'alignment_method': 'error',
            'lossless_match': 0,
            'processing_time_ms': elapsed_ms
        }


def load_manual_csv() -> pd.DataFrame:
    """
    Load manual platform_manifest.csv log.

    Returns:
        DataFrame with manual log data
    """
    csv_path = PLATFORM_TESTS_BASE / "platform_manifest.csv"

    if not csv_path.exists():
        logging.warning("platform_manifest.csv not found - returning empty DataFrame")
        return pd.DataFrame()

    try:
        df = pd.read_csv(csv_path)
        logging.info(f"Loaded {len(df)} rows from platform_manifest.csv")
        return df
    except Exception as e:
        logging.error(f"Failed to load platform_manifest.csv: {e}")
        return pd.DataFrame()


def process_platform_returns() -> List[Dict]:
    """
    Process all platform return files.

    Returns:
        List of result dictionaries
    """
    results = []

    # Scan all platform returned folders
    platforms = ['instagram', 'twitter', 'facebook', 'youtube', 'tiktok', 'whatsapp']

    for platform in platforms:
        # Handle WhatsApp's special folder structure (compressed/file_mode subdirectories)
        if platform == 'whatsapp':
            whatsapp_dirs = [
                PLATFORM_TESTS_BASE / platform / "compressed" / "returned",
                PLATFORM_TESTS_BASE / platform / "file_mode" / "returned"
            ]
            returned_files = []
            for wdir in whatsapp_dirs:
                if wdir.exists():
                    files = list(wdir.glob("*.*"))
                    files = [f for f in files if f.suffix.lower() in ['.mp4', '.jpg', '.png', '.jpeg', '.mov', '.avi']]
                    returned_files.extend(files)
        else:
            returned_dir = PLATFORM_TESTS_BASE / platform / "returned"
            if not returned_dir.exists():
                continue
            returned_files = list(returned_dir.glob("*.*"))
            returned_files = [f for f in returned_files if f.suffix.lower() in ['.mp4', '.jpg', '.png', '.jpeg', '.mov', '.avi']]

        if not returned_files:
            continue

        logging.info(f"Processing {len(returned_files)} files from {platform}")

        for file_path in returned_files:
            logging.info(f"  Processing: {file_path.name}")

            # Parse filename
            parsed = parse_filename(file_path.name)
            if not parsed:
                logging.warning(f"  Skipping (invalid filename): {file_path.name}")
                continue

            # Determine asset type
            asset_type = 'video' if parsed['extension'] in ['mp4', 'mov', 'avi'] else 'image'

            # Find original signed asset
            original_path = find_original_asset(parsed['original_filename'], asset_type)
            if not original_path:
                logging.warning(f"  Skipping (original not found): {file_path.name}")
                continue

            # Run C2PA verification
            c2pa_results = verify_c2pa(file_path)

            # Calculate quality metrics
            if asset_type == 'image':
                quality_results = calculate_image_metrics(original_path, file_path)
            else:
                quality_results = calculate_video_vmaf(original_path, file_path)

            # Compile result (matching final_metrics.csv schema from merge_results.py)
            result = {
                # Core metadata
                'filename': file_path.name,
                'asset_type': asset_type,
                'transform_type': 'platform_roundtrip',
                'transform_level': 'platform_roundtrip',
                'seed': '',  # Will extract from filename
                'model_version': '',  # Will extract from filename

                # C2PA verification metrics
                'manifest_present': c2pa_results['manifest_present'],
                'verified': c2pa_results['verified'],
                'signature_valid': c2pa_results['signature_valid'],
                'hash_match': c2pa_results['hash_match'],
                'assertion_uris_match': c2pa_results['assertion_uris_match'],
                'trust_verified': c2pa_results['trust_verified'],
                'validation_state': c2pa_results['validation_state'],
                'failure_reason': c2pa_results['failure_reason'],

                # Quality metrics
                'psnr': quality_results['psnr'],
                'psnr_aligned': quality_results.get('psnr_aligned', 'NA'),
                'ssim': quality_results['ssim'],
                'ssim_aligned': quality_results.get('ssim_aligned', 'NA'),
                'vmaf': quality_results['vmaf'],
                'vmaf_aligned': quality_results.get('vmaf_aligned', 'NA'),
                'alignment_method': quality_results.get('alignment_method', 'NA'),
                'lossless_match': quality_results['lossless_match'],
                'lossless_transform': 0,
                'processing_time_ms': f"{quality_results['processing_time_ms']:.2f}",
                'calculation_error': 'NA',  # Quality metrics calculated successfully
                'timestamp': datetime.now().isoformat(),

                # Phase 2.5 platform-specific columns
                'platform': platform,
                'platform_mode': parsed['mode'],
                'media_source': detect_media_source(parsed['original_filename']),
                'upload_timestamp': '',  # Will be filled from manual CSV if available
                'download_timestamp': parsed['timestamp']
            }

            # Extract seed from filename (use 'NA' for external sources)
            seed_match = re.search(r'seed(\d+)', parsed['original_filename'])
            if seed_match:
                result['seed'] = seed_match.group(1)
            elif result['media_source'] == 'external':
                result['seed'] = 'NA'

            # Model version (use detection function)
            result['model_version'] = get_model_version(parsed['original_filename'], asset_type, result['media_source'])

            results.append(result)

    return results


def merge_with_manual_csv(results: List[Dict], manual_df: pd.DataFrame) -> pd.DataFrame:
    """
    Merge automated results with manual CSV log.

    Args:
        results: List of automated result dicts
        manual_df: Manual CSV DataFrame

    Returns:
        Merged DataFrame
    """
    results_df = pd.DataFrame(results)

    if manual_df.empty:
        logging.warning("No manual CSV data to merge")
        return results_df

    # Merge on filename match (original_filename in results, original_filename in manual_df)
    # Manual CSV has: original_filename, platform, mode, upload_timestamp, download_timestamp, notes

    # Create join key
    results_df['join_key'] = results_df['original_filename'] + '__' + results_df['platform'] + '__' + results_df['platform_mode']
    manual_df['join_key'] = manual_df['original_filename'] + '__' + manual_df['platform'] + '__' + manual_df['mode']

    # Merge
    merged_df = results_df.merge(
        manual_df[['join_key', 'upload_timestamp', 'notes']],
        on='join_key',
        how='left'
    )

    # Update upload_timestamp if available
    if 'upload_timestamp' in merged_df.columns:
        results_df['upload_timestamp'] = merged_df['upload_timestamp']

    # Drop join key
    results_df.drop(columns=['join_key'], inplace=True, errors='ignore')

    return results_df


def main():
    """Main entry point."""
    logging.info("="*60)
    logging.info("Platform Returns Processing - C2PA Robustness Testing")
    logging.info(f"Python version: {sys.version}")
    logging.info("="*60)

    # Check dependencies
    try:
        subprocess.run([str(C2PATOOL_PATH), '--version'], capture_output=True, check=True, timeout=10)
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        logging.error(f"c2patool not found at {C2PATOOL_PATH}! Please check installation.")
        sys.exit(1)

    try:
        subprocess.run(['ffmpeg', '-version'], capture_output=True, check=True, timeout=10)
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        logging.error("ffmpeg not found! Please install ffmpeg with libvmaf support.")
        sys.exit(1)

    # Process platform returns
    logging.info("Processing platform return files...")
    results = process_platform_returns()

    if not results:
        logging.warning("No platform return files found to process!")
        logging.info("Expected files in: data/platform_tests/*/returned/")
        logging.info("File naming convention: {original}__{platform}__{mode}__{timestamp}.{ext}")
        sys.exit(0)

    logging.info(f"Processed {len(results)} platform return files")

    # Load manual CSV
    logging.info("Loading manual CSV log...")
    manual_df = load_manual_csv()

    # Merge with manual data
    logging.info("Merging with manual log data...")
    final_df = merge_with_manual_csv(results, manual_df)

    # Save results
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = RESULTS_DIR / "platform_results.csv"

    final_df.to_csv(output_path, index=False)
    logging.info(f"Saved results to: {output_path}")
    logging.info(f"  Total rows: {len(final_df)}")
    logging.info(f"  Columns: {len(final_df.columns)}")

    # Print summary
    logging.info("="*60)
    logging.info("Platform Results Summary")
    logging.info(f"  Total files processed: {len(final_df)}")
    logging.info(f"  Manifests present: {final_df['manifest_present'].sum()}")
    logging.info(f"  Verified: {final_df['verified'].sum()}")
    logging.info(f"  Manifest stripped: {len(final_df) - final_df['manifest_present'].sum()}")
    logging.info("="*60)

    # Per-platform summary
    logging.info("Per-Platform Breakdown:")
    for platform in final_df['platform'].unique():
        platform_df = final_df[final_df['platform'] == platform]
        logging.info(f"  {platform}:")
        logging.info(f"    Files: {len(platform_df)}")
        logging.info(f"    Manifests present: {platform_df['manifest_present'].sum()}")
        logging.info(f"    Verified: {platform_df['verified'].sum()}")

    logging.info("="*60)
    logging.info("Next step: Run scripts/metrics/merge_results.py to merge with final_metrics.csv")


if __name__ == "__main__":
    main()
